spring:
  application:
    name: medimind
  
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  ai:
    google:
      genai:
        api-key: ${GOOGLE_AI_API_KEY}
        chat:
          options:
            model: gemini-pro

  mail:
    host: ${EMAIL_HOST}
    port: ${EMAIL_PORT}
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/api/oauth/google/callback"
            authorization-grant-type: authorization_code
            scope:
              - https://www.googleapis.com/auth/calendar
              - https://www.googleapis.com/auth/calendar.events
              - email
              - profile

app:
  oauth2:
    authorized-redirect-uri: http://localhost:3000/oauth2/redirect

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: 3600000
  refresh-token-expiration: 604800000



logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.ai: DEBUG
